# Generated by Django 3.0.5 on 2020-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('email_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MyMailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.EmailField(max_length=254)),
                ('mail_content', models.CharField(max_length=3000)),
                ('mail_subject', models.CharField(max_length=1000)),
                ('mail_attachment', models.FileField(blank=True, upload_to='attachment/')),
            ],
        ),
    ]
